# Site settings
title: Leon
description: Those who are calm must have their own landscape.
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: "/leon-1996/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://leon-1996.github.io" # the base hostname & protocol for your site

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  per_page: 5

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate-v2


# Settings for rake task
safe: False
lsi: False
username: leon-1996 #github username
repo: leon-1996 #github repository
branch: master #branch
relative_source: ../leon-1996/ #source directory
destination: ../leon-1996-pages/ #destination directory
production_url:  https://leon-1996.github.io/
source_url:  https://leon-1996.github.io/leon-1996 #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
